export type TriviaQuestion = {
  id: string;
  question: string;
  options: string[];
  answer: string;
};

export const TRIVIA_QUESTIONS: TriviaQuestion[] = [
  { id: "t1", question: "What is the capital city of Ghana?", options: ["Kumasi", "Accra", "Tamale", "Takoradi"], answer: "Accra" },
  { id: "t2", question: "Which planet is known as the Red Planet?", options: ["Venus", "Mars", "Jupiter", "Mercury"], answer: "Mars" },
  { id: "t3", question: "Which ocean is the largest?", options: ["Atlantic", "Indian", "Pacific", "Arctic"], answer: "Pacific" },
  { id: "t4", question: "How many sides does a hexagon have?", options: ["5", "6", "7", "8"], answer: "6" },
  { id: "t5", question: "Which gas do plants absorb from the atmosphere?", options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"], answer: "Carbon Dioxide" },
  { id: "t6", question: "What is the largest continent by land area?", options: ["Africa", "Asia", "Europe", "North America"], answer: "Asia" },
  { id: "t7", question: "Which organ pumps blood around the human body?", options: ["Brain", "Liver", "Heart", "Lungs"], answer: "Heart" },
  { id: "t8", question: "Which country is home to the Pyramids of Giza?", options: ["Sudan", "Egypt", "Morocco", "Ethiopia"], answer: "Egypt" },
  { id: "t9", question: "What is the freezing point of water in Celsius?", options: ["0", "10", "32", "100"], answer: "0" },
  { id: "t10", question: "Which animal is the largest living land animal?", options: ["Giraffe", "Hippopotamus", "African Elephant", "Rhinoceros"], answer: "African Elephant" },
  { id: "t11", question: "What is the chemical symbol for gold?", options: ["Ag", "Au", "Fe", "Go"], answer: "Au" },
  { id: "t12", question: "Which planet is the largest in the Solar System?", options: ["Saturn", "Earth", "Jupiter", "Neptune"], answer: "Jupiter" },
  { id: "t13", question: "How many bones are typically in an adult human body?", options: ["196", "206", "216", "226"], answer: "206" },
  { id: "t14", question: "Which blood cells primarily help fight infection?", options: ["Red blood cells", "White blood cells", "Platelets", "Plasma"], answer: "White blood cells" },
  { id: "t15", question: "What is the hardest natural substance?", options: ["Iron", "Quartz", "Diamond", "Granite"], answer: "Diamond" },
  { id: "t16", question: "Which instrument measures atmospheric pressure?", options: ["Thermometer", "Barometer", "Hygrometer", "Altimeter"], answer: "Barometer" },
  { id: "t17", question: "What is the smallest prime number?", options: ["0", "1", "2", "3"], answer: "2" },
  { id: "t18", question: "Which country has the city of Nairobi as its capital?", options: ["Kenya", "Uganda", "Tanzania", "Rwanda"], answer: "Kenya" },
  { id: "t19", question: "Which layer of Earth is liquid and surrounds the inner core?", options: ["Crust", "Mantle", "Outer core", "Lithosphere"], answer: "Outer core" },
  { id: "t20", question: "What is the process by which plants make food using sunlight?", options: ["Respiration", "Photosynthesis", "Fermentation", "Transpiration"], answer: "Photosynthesis" },
  { id: "t21", question: "Which country is the largest in Africa by land area?", options: ["Nigeria", "Sudan", "Algeria", "DR Congo"], answer: "Algeria" },
  { id: "t22", question: "What is the capital of Nigeria?", options: ["Lagos", "Abuja", "Kano", "Ibadan"], answer: "Abuja" },
  { id: "t23", question: "Which element has the chemical symbol O?", options: ["Gold", "Oxygen", "Osmium", "Silver"], answer: "Oxygen" },
  { id: "t24", question: "How many degrees are in a right angle?", options: ["45", "90", "180", "360"], answer: "90" },
  { id: "t25", question: "Which part of a plant mainly absorbs water from the soil?", options: ["Flower", "Leaf", "Root", "Fruit"], answer: "Root" },
  { id: "t26", question: "Which planet is closest to the Sun?", options: ["Venus", "Earth", "Mercury", "Mars"], answer: "Mercury" },
  { id: "t27", question: "Which African country was formerly known as the Gold Coast?", options: ["Ghana", "Nigeria", "Liberia", "Senegal"], answer: "Ghana" },
  { id: "t28", question: "What is the capital of Senegal?", options: ["Dakar", "Bamako", "Conakry", "Lomé"], answer: "Dakar" },
  { id: "t29", question: "Which organ is primarily responsible for filtering blood and producing urine?", options: ["Heart", "Kidneys", "Lungs", "Pancreas"], answer: "Kidneys" },
  { id: "t30", question: "Which gas is most abundant in Earth's atmosphere?", options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"], answer: "Nitrogen" },
  { id: "t31", question: "Which continent contains the Sahara Desert?", options: ["Asia", "Africa", "Australia", "South America"], answer: "Africa" },
  { id: "t32", question: "What is the capital of Japan?", options: ["Kyoto", "Tokyo", "Osaka", "Nagoya"], answer: "Tokyo" },
  { id: "t33", question: "Which planet is famous for its prominent ring system?", options: ["Mars", "Saturn", "Mercury", "Venus"], answer: "Saturn" },
  { id: "t34", question: "What is 15 squared?", options: ["125", "200", "225", "250"], answer: "225" },
  { id: "t35", question: "Which metal is liquid at standard room temperature?", options: ["Mercury", "Iron", "Copper", "Aluminium"], answer: "Mercury" },
  { id: "t36", question: "Which country has the largest population in Africa?", options: ["Egypt", "Ethiopia", "Nigeria", "South Africa"], answer: "Nigeria" },
  { id: "t37", question: "What is the capital city of Canada?", options: ["Toronto", "Vancouver", "Ottawa", "Montreal"], answer: "Ottawa" },
  { id: "t38", question: "Which vitamin is mainly produced in human skin through sunlight exposure?", options: ["Vitamin A", "Vitamin C", "Vitamin D", "Vitamin K"], answer: "Vitamin D" },
  { id: "t39", question: "What is the largest internal organ in the human body?", options: ["Heart", "Liver", "Lung", "Kidney"], answer: "Liver" },
  { id: "t40", question: "Which country is Mount Kilimanjaro located in?", options: ["Kenya", "Tanzania", "Uganda", "Ethiopia"], answer: "Tanzania" },
  { id: "t41", question: "What is the capital of Australia?", options: ["Sydney", "Melbourne", "Canberra", "Perth"], answer: "Canberra" },
  { id: "t42", question: "Which is the largest organ of the human body?", options: ["Liver", "Brain", "Skin", "Lungs"], answer: "Skin" },
  { id: "t43", question: "What is the square root of 144?", options: ["10", "11", "12", "14"], answer: "12" },
  { id: "t44", question: "Which scientist formulated the three laws of motion?", options: ["Albert Einstein", "Isaac Newton", "Galileo Galilei", "Charles Darwin"], answer: "Isaac Newton" },
  { id: "t45", question: "Which country is known as the Land of the Rising Sun?", options: ["China", "Japan", "Thailand", "South Korea"], answer: "Japan" },
  { id: "t46", question: "Which sea separates Europe and Africa?", options: ["Red Sea", "Mediterranean Sea", "Black Sea", "Arabian Sea"], answer: "Mediterranean Sea" },
  { id: "t47", question: "Which part of the human eye controls the amount of light entering?", options: ["Retina", "Iris", "Cornea", "Optic nerve"], answer: "Iris" },
  { id: "t48", question: "What is the chemical formula for water?", options: ["CO2", "H2O", "O2", "NaCl"], answer: "H2O" },
  { id: "t49", question: "Which continent is Brazil located in?", options: ["North America", "Africa", "South America", "Europe"], answer: "South America" },
  { id: "t50", question: "What is the capital of Ethiopia?", options: ["Addis Ababa", "Nairobi", "Khartoum", "Kigali"], answer: "Addis Ababa" },
  { id: "t51", question: "Which part of the brain is mainly responsible for balance and coordination?", options: ["Cerebrum", "Cerebellum", "Medulla", "Hypothalamus"], answer: "Cerebellum" },
  { id: "t52", question: "What is 13 multiplied by 12?", options: ["146", "156", "166", "176"], answer: "156" },
  { id: "t53", question: "Which country has Cairo as its capital?", options: ["Egypt", "Libya", "Sudan", "Tunisia"], answer: "Egypt" },
  { id: "t54", question: "Which natural satellite orbits Earth?", options: ["Mars", "Moon", "Sun", "Venus"], answer: "Moon" },
  { id: "t55", question: "Which is the longest bone in the human body?", options: ["Tibia", "Femur", "Humerus", "Fibula"], answer: "Femur" },
  { id: "t56", question: "What is the capital of Rwanda?", options: ["Kigali", "Kampala", "Bujumbura", "Nairobi"], answer: "Kigali" },
  { id: "t57", question: "Which instrument is used to detect and record earthquakes?", options: ["Barometer", "Seismograph", "Thermometer", "Anemometer"], answer: "Seismograph" },
  { id: "t58", question: "What is the largest species of shark?", options: ["Great white shark", "Hammerhead shark", "Whale shark", "Tiger shark"], answer: "Whale shark" },
  { id: "t59", question: "Which element has atomic number 1?", options: ["Helium", "Hydrogen", "Oxygen", "Carbon"], answer: "Hydrogen" },
  { id: "t60", question: "What is the capital of France?", options: ["Lyon", "Paris", "Marseille", "Nice"], answer: "Paris" },
  { id: "t61", question: "How many chambers does the human heart have?", options: ["2", "3", "4", "5"], answer: "4" },
  { id: "t62", question: "Which country is home to the ancient city of Petra?", options: ["Jordan", "Egypt", "Greece", "Turkey"], answer: "Jordan" },
  { id: "t63", question: "What is the largest planet in our Solar System?", options: ["Earth", "Saturn", "Jupiter", "Neptune"], answer: "Jupiter" },
  { id: "t64", question: "Which organ produces insulin?", options: ["Liver", "Pancreas", "Kidney", "Stomach"], answer: "Pancreas" },
  { id: "t65", question: "What is the capital of South Africa's administrative branch?", options: ["Cape Town", "Pretoria", "Bloemfontein", "Johannesburg"], answer: "Pretoria" },
  { id: "t66", question: "Which force keeps planets in orbit around the Sun?", options: ["Magnetism", "Gravity", "Friction", "Electricity"], answer: "Gravity" },
  { id: "t67", question: "Which is the smallest continent by land area?", options: ["Europe", "Antarctica", "Australia", "South America"], answer: "Australia" },
  { id: "t68", question: "What is the capital of Italy?", options: ["Milan", "Rome", "Venice", "Naples"], answer: "Rome" },
  { id: "t69", question: "Which type of blood vessel carries blood away from the heart?", options: ["Vein", "Artery", "Capillary", "Valve"], answer: "Artery" },
  { id: "t70", question: "What is 25 percent of 200?", options: ["25", "40", "50", "75"], answer: "50" },
  { id: "t71", question: "Which country is home to Machu Picchu?", options: ["Chile", "Peru", "Brazil", "Mexico"], answer: "Peru" },
  { id: "t72", question: "What is the capital of Germany?", options: ["Munich", "Frankfurt", "Berlin", "Hamburg"], answer: "Berlin" },
  { id: "t73", question: "Which gas is essential for human respiration?", options: ["Nitrogen", "Oxygen", "Carbon Dioxide", "Helium"], answer: "Oxygen" },
  { id: "t74", question: "What is the largest mammal on Earth?", options: ["African Elephant", "Blue Whale", "Giraffe", "Hippopotamus"], answer: "Blue Whale" },
  { id: "t75", question: "Which country has Brasília as its capital?", options: ["Argentina", "Brazil", "Portugal", "Colombia"], answer: "Brazil" },
  { id: "t76", question: "Which branch of science studies living organisms?", options: ["Physics", "Biology", "Geology", "Astronomy"], answer: "Biology" },
  { id: "t77", question: "How many players does a football team normally have on the field at one time?", options: ["9", "10", "11", "12"], answer: "11" },
  { id: "t78", question: "What is the capital of Kenya?", options: ["Mombasa", "Nairobi", "Kisumu", "Nakuru"], answer: "Nairobi" },
  { id: "t79", question: "Which organ is mainly responsible for breathing?", options: ["Heart", "Lungs", "Liver", "Kidneys"], answer: "Lungs" },
  { id: "t80", question: "What is the value of 7 cubed?", options: ["49", "243", "343", "441"], answer: "343" },
  { id: "t81", question: "Which country is the world's largest by land area?", options: ["Canada", "China", "Russia", "United States"], answer: "Russia" },
  { id: "t82", question: "Which planet is sometimes called Earth's twin because of its similar size?", options: ["Mars", "Venus", "Mercury", "Neptune"], answer: "Venus" },
  { id: "t83", question: "What is the capital of Spain?", options: ["Barcelona", "Madrid", "Valencia", "Seville"], answer: "Madrid" },
  { id: "t84", question: "Which human body system includes the brain and spinal cord?", options: ["Digestive system", "Nervous system", "Respiratory system", "Skeletal system"], answer: "Nervous system" },
  { id: "t85", question: "What is 18 multiplied by 7?", options: ["116", "126", "136", "146"], answer: "126" },
  { id: "t86", question: "Which country has the maple leaf on its national flag?", options: ["Canada", "Australia", "New Zealand", "Ireland"], answer: "Canada" },
  { id: "t87", question: "Which part of a cell contains most of its genetic material?", options: ["Cell membrane", "Nucleus", "Cytoplasm", "Ribosome"], answer: "Nucleus" },
  { id: "t88", question: "What is the capital of Uganda?", options: ["Kampala", "Kigali", "Nairobi", "Dodoma"], answer: "Kampala" },
  { id: "t89", question: "Which unit is used to measure electric current?", options: ["Volt", "Ampere", "Watt", "Ohm"], answer: "Ampere" },
  { id: "t90", question: "Which country contains the city of Dubai?", options: ["Saudi Arabia", "Qatar", "United Arab Emirates", "Kuwait"], answer: "United Arab Emirates" },
  { id: "t91", question: "How many teeth does a typical healthy adult human have?", options: ["28", "30", "32", "36"], answer: "32" },
  { id: "t92", question: "Which planet takes the longest time to orbit the Sun?", options: ["Saturn", "Uranus", "Neptune", "Jupiter"], answer: "Neptune" },
  { id: "t93", question: "What is the capital of Morocco?", options: ["Casablanca", "Rabat", "Marrakesh", "Fez"], answer: "Rabat" },
  { id: "t94", question: "Which process changes liquid water into water vapour?", options: ["Condensation", "Evaporation", "Freezing", "Precipitation"], answer: "Evaporation" },
  { id: "t95", question: "What is 144 divided by 12?", options: ["10", "11", "12", "14"], answer: "12" },
  { id: "t96", question: "Which country is home to the Great Barrier Reef?", options: ["Australia", "Indonesia", "Philippines", "New Zealand"], answer: "Australia" },
  { id: "t97", question: "Which mineral is essential for strong bones and teeth?", options: ["Iron", "Calcium", "Sodium", "Potassium"], answer: "Calcium" },
  { id: "t98", question: "What is the capital of Tanzania?", options: ["Dar es Salaam", "Dodoma", "Arusha", "Mwanza"], answer: "Dodoma" },
  { id: "t99", question: "Which instrument is used to measure temperature?", options: ["Barometer", "Thermometer", "Seismograph", "Compass"], answer: "Thermometer" },
  { id: "t100", question: "What is the largest hot desert in the world?", options: ["Gobi", "Kalahari", "Sahara", "Arabian"], answer: "Sahara" },
];
